"use client";

import { useMemo, useState, useTransition } from "react";

import {
  createPr,
  draftReadme,
  type DraftReadmeResponse,
  type Profile,
} from "@/lib/api";

type Phase = "pick" | "drafting" | "review" | "creating" | "done" | "error";

export function ReadmeWriter({
  profile,
  onClose,
}: {
  profile: Profile;
  onClose: () => void;
}) {
  const ownedRepos = useMemo(
    () =>
      profile.projects
        .filter((p) => !!p.repo_url && p.repo_url.includes("/"))
        .map((p) => {
          const url = new URL(p.repo_url!);
          const [, owner, repo] = url.pathname.split("/");
          return { owner, repo, name: p.name, stars: p.stars };
        }),
    [profile.projects],
  );

  const [selected, setSelected] = useState(ownedRepos[0]);
  const [phase, setPhase] = useState<Phase>("pick");
  const [draft, setDraft] = useState<DraftReadmeResponse | null>(null);
  const [content, setContent] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [prUrl, setPrUrl] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();

  function fetchDraft() {
    if (!selected) return;
    setError(null);
    setPhase("drafting");
    startTransition(async () => {
      try {
        const d = await draftReadme(selected.owner, selected.repo);
        setDraft(d);
        setContent(d.proposed);
        setPhase("review");
      } catch (e) {
        setError(e instanceof Error ? e.message : "Failed to draft README");
        setPhase("error");
      }
    });
  }

  function openPr() {
    if (!draft) return;
    setError(null);
    setPhase("creating");
    startTransition(async () => {
      try {
        const branch = `chore/readme-${Date.now()}`;
        const result = await createPr({
          owner: draft.owner,
          repo: draft.repo,
          branch,
          file_path: draft.file_path,
          content,
          sha: draft.current_sha,
          commit_message: "docs: refresh README via ai-portfolio-agent",
          pr_title: "docs: refresh README",
          pr_body:
            "Generated by ai-portfolio-agent's README Update Agent.\n\n" +
            draft.summary,
          base: draft.default_branch,
        });
        setPrUrl(result.pr_url);
        setPhase("done");
      } catch (e) {
        setError(e instanceof Error ? e.message : "Failed to open PR");
        setPhase("error");
      }
    });
  }

  return (
    <div className="rounded-lg border border-[var(--border)] bg-[var(--muted)] p-4">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-medium text-neutral-200">
          README Update Agent
        </h3>
        <button
          onClick={onClose}
          className="text-xs text-neutral-500 hover:text-neutral-300"
        >
          close
        </button>
      </div>

      {ownedRepos.length === 0 ? (
        <p className="text-sm text-neutral-400">
          No repositories on this profile to update.
        </p>
      ) : null}

      {ownedRepos.length > 0 && phase === "pick" ? (
        <>
          <label className="text-xs text-neutral-500">Pick a repository</label>
          <select
            value={selected ? `${selected.owner}/${selected.repo}` : ""}
            onChange={(e) => {
              const [owner, repo] = e.target.value.split("/");
              const r = ownedRepos.find(
                (x) => x.owner === owner && x.repo === repo,
              );
              if (r) setSelected(r);
            }}
            className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 py-2 text-sm outline-none focus:border-[var(--accent-soft)]"
          >
            {ownedRepos.map((r) => (
              <option key={`${r.owner}/${r.repo}`} value={`${r.owner}/${r.repo}`}>
                {r.owner}/{r.repo} ({r.stars}★)
              </option>
            ))}
          </select>
          <div className="mt-3 flex justify-end">
            <button
              onClick={fetchDraft}
              disabled={pending || !selected}
              className="rounded-md bg-[var(--accent)] px-3 py-1.5 text-xs font-medium text-white transition hover:bg-[var(--accent-soft)] disabled:opacity-50"
            >
              Draft proposal
            </button>
          </div>
        </>
      ) : null}

      {phase === "drafting" ? (
        <p className="text-sm text-neutral-400">Drafting README...</p>
      ) : null}

      {phase === "review" && draft ? (
        <>
          <p className="text-xs text-neutral-500">{draft.summary}</p>
          <p className="mt-2 text-xs text-neutral-500">
            Editable - review before opening a PR against{" "}
            <span className="text-neutral-300">
              {draft.owner}/{draft.repo}@{draft.default_branch}
            </span>
            .
          </p>
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            rows={16}
            className="mt-2 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] p-3 font-mono text-xs text-neutral-200 outline-none focus:border-[var(--accent-soft)]"
          />
          <div className="mt-3 flex justify-end gap-2">
            <button
              onClick={() => setPhase("pick")}
              className="rounded-md border border-[var(--border)] px-3 py-1.5 text-xs text-neutral-400 hover:text-neutral-200"
            >
              Back
            </button>
            <button
              onClick={openPr}
              disabled={pending || content.trim().length === 0}
              className="rounded-md bg-[var(--accent)] px-3 py-1.5 text-xs font-medium text-white transition hover:bg-[var(--accent-soft)] disabled:opacity-50"
            >
              Open PR
            </button>
          </div>
        </>
      ) : null}

      {phase === "creating" ? (
        <p className="text-sm text-neutral-400">Branching, committing, opening PR...</p>
      ) : null}

      {phase === "done" && prUrl ? (
        <div className="rounded-lg border border-emerald-700/40 bg-emerald-900/10 p-3">
          <p className="text-sm text-emerald-300">PR opened.</p>
          <a
            href={prUrl}
            target="_blank"
            rel="noreferrer"
            className="mt-1 block break-all text-xs text-emerald-200 underline"
          >
            {prUrl}
          </a>
        </div>
      ) : null}

      {phase === "error" && error ? (
        <p className="mt-2 text-xs text-red-400">{error}</p>
      ) : null}
    </div>
  );
}
